## Example Config file
baseURL: "https://nikobonomi.dev"
theme: "terminalcv"
title: "nikobonomi.dev"

params:
  version: "2.0.0"
  description: "Niko Bonomi CV"
  blog: false
  prompt:
    core:
      text: "guest@nikobonomi.dev"
      color: "pink"
      before: "["
      beforeColor: "red"
      after: '\]'
      afterColor: "red"
      # separator: '-'
    separator:
      text: "-"
      # color:
    path:
      before: "["
      beforeColor: "red"
      text: "~/home"
      color: "green"
      after: '\]'
      afterColor: "red"
    extra:
      text: ": "
      color: "orange"

  # promptColor: grey
  # promptSimbols: ":~$"
  # promptSimbolsColor: grey
  # startxLocation: https://example.com
  # useLess: true
  listLS: true
  #exitLocation: "about:blank"
  exitMessage: "[Session completed, the browserwindow can be safely closed]"
  source: false
  #use a â€Ž (blank character) if your first character of the ascii art is a whitespace
  greeting: |
    â€Ž
     _   _ _ _          _______      __
    | \ | (_) |        / ____\ \    / /
    |  \| |_| | _____ | |     \ \  / / 
    | . ` | | |/ / _ \| |      \ \/ /  
    | |\  | |   < (_) | |____   \  /   
    |_| \_|_|_|\_\___/ \_____|   \/    
                                                                
    Hello there!
    Iâ€™m Niko, a â€œfull-stackâ€ software engineer

    I currently work @ Swiss Post, actively developing modern solutions for customers and internal consumers.

    Start by typing 'help' for a list of available commands

  bootsequence: |
    User request detected
    Allocating Resources for: Niko Bonomi
    â†’ Provisioning Developer Environment
    ............................
    ðŸ”ï¸ Location: Lamone, CH
    ..................
    ðŸ¢ Affiliation: Swiss Post Ltd
    ......
    ðŸ” Profiling Expertise: DevOps, Backend, Cloud, Research
    .......................
    Internet Breakout Ready â€” but 'ping nikobonomi.dev' is faster
    
    Booting TerminalCV [v1.0.0-niko]
    Kernel build: Sat Feb 29 23:21:41 CEST 2025; niko:xnu-1699.22.73~dev64
    Loglevel = quiet
    .........system warming up..........
    ......building resume kernel modules......
    â†ªï¸ java, spring, docker, k8s, git, postgres
    â†ªï¸ angularjs, python, aws, argocd
    â†ªï¸ mentoring, team-work, time-management
    â†ªï¸ italian ðŸ‡®ðŸ‡¹ / english ðŸ‡¬ðŸ‡§ / french ðŸ‡«ðŸ‡· / german ðŸ‡©ðŸ‡ª
    .................
    TerminalCV Init Sequence
    â†’ Welcome Niko Bonomi
    â†’ Role: Software Developer | Explorer of Systems
    â†’ Motto: *Build things that scale, and help others do the same*
    ..........................
    ðŸ§  Education Modules:
    âœ“ MSc IoT @ SUPSI
    âœ“ BSc SE + Apprenticeship @ SPAI Locarno
    .......................
    
    All packets reserved â€” All bugs intentional ðŸ›
    
    [CV_Core]: loaded
    [HUGO Server]: online
    [Web Frontend]: active
    [Terminal I/O]: accepting commands
    
    > Boot Completes

  whois:
    # settings:
    #   useLess: true
    details:
      name: "Niko Bonomi"
      profession: "Software Developer"
      location: "Lamone"
      email: "niko.bonomi@gmail.com"
      homelink: "https://nikobonomi.dev"
      description: |
        Software Engineer by trade, system tinkerer by passion.
        DevOps, backend, containers and clouds are my playground.
        I build, break, fix â€” then automate it all.

  social:
    # settings:
    #   useLess: true
    #   hideName: true
    details:
      - name: "Linkedin"
        url: "https://www.linkedin.com/in/nikobonomi/?locale=en_US"
      - name: "Google Scholar"
        url: "https://scholar.google.com/citations?user=dsx_h0kAAAAJ"

  work:
    # settings:
    #   useLess: true
    details:
      - jobTitle: DevOps Software Engineer
        #color: yellow
        company: "Swiss Post Ltd"
        location: Bellinzona
        date: 2023 - Present
        description: |
          Developing a cloud-native web application for managing delivery preferences at Swiss Post.
          Working across the stack (Spring + Angular), integrating with internal services via REST and Kafka,
          and deploying on Kubernetes with containerized workflows.

      - jobTitle: Applied research - Software development
        company: "University of Applied Sciences and Arts Southern Switzerland"
        location: Lugano
        date: 2019 - 2023
        description: |
          Developed web-based platforms and REST APIs for applied research projects at SUPSI, with a strong focus
          on integration between software and hardware systems. Contributed to the Mini-Factory project,
          supporting industrial automation research. Active in Swiss and EU-funded initiatives, covering both
          implementation and technical coordination tasks

      - jobTitle: Software Developer
        company: "Cantonal Hospital - EOC"
        location: Bellinzona
        date: 2014 - 2018
        description: |
          Developed and maintained custom integrations between the CA Service Desk system and internal applications
          within the hospitalâ€™s IT ecosystem. Focused on backend development and automation of service workflows.
          Initially employed full-time, later reduced to part-time to pursue academic studies while continuing
          active development work in a complex enterprise environment.

      - jobTitle: Software developer apprenticeship
        company: "Cantonal Hospital - EOC"
        location: Bellinzona
        date: 2009 - 2013
        description: |
          Started my professional journey as a software developer apprentice at EOC's IT department,
          gaining hands-on experience with .NET technologies under the guidance of senior developers.
          Combined practical training with in-class learning, expanding my knowledge in Java, C, and JavaScript.
          Built a solid foundation in software engineering principles and enterprise IT systems.

  education:
    details:
      - courseName: Master of Science in Engineering - MSE
        date: 2019 - 2022
        description: With specialization in "Internet of Things" @ SUPSI Lugano

      - courseName: Bachelor Of Science
        date: 2014 - 2018
        description: Software Engineering @ SUPSI Lugano

      - courseName: Computer Science Apprenticeship, specialization in software development
        date: 2014 - 2018
        description: EFZ (Federal Vocational Certificate) and TALS (vocational baccalaureate in technology) @ SPAI Locarno

  skills:
    settings:
      useLess: false
    details:
      - name: Java
        percentage: 98

      - name: Spring Framework
        percentage: 90

      - name: Python
        percentage: 70
        #description: or you can leave it comented
        #color: blue

      - name: PostgreSQL
        percentage: 80

      - name: Amazon Web Services 
        percentage: 50

      - name: Kubernetes
        percentage: 80

      - name: Javasscript/AngularJS
        percentage: 80

      - name: Docker
        percentage: 90

      - name: GitHub Actions
        percentage: 80

      - name: ArgoCD
        percentage: 80

  softskills:
    # settings:
    #   useLess: true
    details:
      - name: Motivation
        #color: red
        #description:
        percentage: 95

      - name: Team-work
        percentage: 100
        
      - name: Leadership
        percentage: 75
        
      - name: Communication
        percentage: 80
        
      - name: Support and Mentoring
        percentage: 90
        
      - name: Time Management
        percentage: 90
        
  languages:
    # settings:
    #   useLess: true
    details:
      - name: Italian
        percentage: 100
        description: Mother tongue

      - name: English
        percentage: 90
        description: B2 (Business)

      - name: French
        percentage: 50
        description: A2 (Good oral skills)

      - name: German
        percentage: 20
        description: A2

#   projects:
#     # settings:
#     #   useLess: true
#     details:
#       - title: Project Red
#         color: red
#         date: since 2019
#         link: https://example.com
#         description: Describing red stuff


  certifications:
    # settings:
    #   useLess: true
    details:
      - certName: Lean IT Foundation
        company: APMG International
        date: 2019
        #badge: https://www.link.to.badge
        #description: Lorem Ipsum

      - certName: COBIT 5 Implementation
        company: APMG International
        date: 2018

      - certName: COBIT 5 Foundation
        company: PeopleCert
        date: 2018

      - certName: ITIL Service Strategy
        company: APMG International
        date: 2017

      - certName: ITIL Service Design
        company: PeopleCert
        date: 2017

      - certName: ITIL Foundation
        company: APMG International
        date: 2015

  miscO:
    # settings:
    #   useLess: true
    commandName: newcommand
    title: "This Section can have a different command name"
    titleColor: teal
    content: |
      Here the title and the content can have different colors
      The content can be multi

      line

      And spaces       will be respected as well
      This section will have the default command: misc
      but you can name it something else with the property
      commandName: <String>
      Give it a shot and try and uncomment the line 
      commandName: newcommand
      now instead of misc you can execute the newcommand for this section
      Auto completion will know it too! :D

    contentColor: orange
